#include "main.h"
#include "uart.h"
#include <string.h>

UART_HandleTypeDef huart1;

#define LED_GPIO_PORT GPIOA
#define LED_GPIO_PIN GPIO_PIN_10

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART1_UART_Init();

    // Init UART task with uart handle and LED pin info
    uart_task_init(&huart1, LED_GPIO_PORT, LED_GPIO_PIN);

    // Start UART RX interrupt for 1 byte
    uint8_t dummy;
    HAL_UART_Receive_IT(&huart1, &dummy, 1);

    uint32_t last_tick = HAL_GetTick();

    while (1)
    {
        int override = uart_task_get_led_override();

        if (override == -1)
        {
            // Blink mode (toggle every 1000ms)
            if (HAL_GetTick() - last_tick >= 1000)
            {
                HAL_GPIO_TogglePin(LED_GPIO_PORT, LED_GPIO_PIN);
                last_tick = HAL_GetTick();
            }
        }
        else if (override == 1)
        {
            // Turn LED ON
            HAL_GPIO_WritePin(LED_GPIO_PORT, LED_GPIO_PIN, GPIO_PIN_SET);
        }
        else
        {
            // Turn LED OFF
            HAL_GPIO_WritePin(LED_GPIO_PORT, LED_GPIO_PIN, GPIO_PIN_RESET);
        }
    }
}

// UART RX callback
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1)
    {
        // Grab received byte
        uint8_t byte = huart->Instance->RDR;  // or use stored rx_data if you used HAL_UART_Receive_IT

        uart_task_process_byte(byte);

        // Restart RX interrupt
        HAL_UART_Receive_IT(&huart1, &byte, 1);
    }
}

// Below are HAL init functions (can be generated by CubeMX or written manually)

void SystemClock_Config(void)
{
    // Your clock config here (generated by CubeMX)
}

void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();

    GPIO_InitTypeDef GPIO_InitStruct = {0};

    GPIO_InitStruct.Pin = LED_GPIO_PIN;
    GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED_GPIO_PORT, &GPIO_InitStruct);
}

void MX_USART1_UART_Init(void)
{
    __HAL_RCC_USART1_CLK_ENABLE();
    __HAL_RCC_GPIOA_CLK_ENABLE();

    // PA9 TX, PA10 RX
    GPIO_InitTypeDef GPIO_InitStruct = {0};

    GPIO_InitStruct.Pin = GPIO_PIN_9;
    GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
    GPIO_InitStruct.Alternate = GPIO_AF1_USART1;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    GPIO_InitStruct.Pin = GPIO_PIN_10;
    GPIO_InitStruct.Mode = GPIO_MODE_INPUT;
    GPIO_InitStruct.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

    huart1.Instance = USART1;
    huart1.Init.BaudRate = 115200;
    huart1.Init.WordLength = UART_WORDLENGTH_8B;
    huart1.Init.StopBits = UART_STOPBITS_1;
    huart1.Init.Parity = UART_PARITY_NONE;
    huart1.Init.Mode = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;

    HAL_UART_Init(&huart1);
}
